// Types for @prisma/client are generated by `prisma generate`.
// If they are missing in the dev environment this import can produce a TS error.
// We temporarily ignore the import error until `prisma generate` has been run.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import { PrismaClient } from '@prisma/client'

declare global {
  // eslint-disable-next-line no-var
  var prisma: PrismaClient | undefined
}

export const prisma = global.prisma ?? new PrismaClient()
if (process.env.NODE_ENV !== 'production') global.prisma = prisma

export default prisma
